apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  labels:
    {{- include "backend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "backend.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | indent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - name: be-port 
              containerPort: {{ .Values.backend.containerPort }}