apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
spec:
  selector:
    {{- include "backend.labels" . | indent 4 }}
  type: {{ .Values.backend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: be-port