apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
  labels:
    {{- include "frontend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "frontend.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | indent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - name: fe-port
              containerPort: {{ .Values.frontend.containerPort }}