apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
    {{- include "member-app-helm.labels" . | nindent 4 }}
    {{- include "member-app-helm.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.services.frontend.type}}
  ports:
    - name: {{ .Values.services.frontend.portName }}
      port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.targetPort }}
      protocol: TCP
  selector:
    {{- include "member-app-helm.frontendLabels" . | nindent 4}}